log_level: debug
working_dir: ./tmp
max_task_duration: 15

rmq:
  server_url: amqp://user:bitnami@rmq:5672/
  job_queue_name: jobs
  result_queue_name: results
  update_queue_name: updates

aws:
  session_token: aws-session-token
  secret_key: aws-secret-key
  region: us-west
